export default {
  SET_LOCALE: 'SET_LOCALE',
  ADD_LOCALE: 'ADD_LOCALE',
  SET_USER: 'SET_USER',
  REMOVE_USER: 'REMOVE_USER',
  SEARCH: 'SEARCH',
  CHANGE_THEME: 'CHANGE_THEME',
  SET_AUTHFORM: 'SET-AUTHFORM',
  SET_SPRINT_ANSWERS: 'SET_SPRINT_ANSWERS',
  SET_SETTINGS: 'SET_SETTINGS',
};
